### ISSUE TITLE
inline styling

### ISSUE THREAD

**Issue by markusfalk** [bkosborne/jQuery-Feature-Carousel#6]
it would help to style elements of the plugin if they were not styles using inline styles

**Comment by bkosborne** [comment]
Can you give me some examples? Whenever jQuery manipulates the elementals, it always uses inline styling. Not much can be done about that.

**Comment by markusfalk** [comment]
.tracker-individual-container li contains inline styles for floating and list-style-type

**Comment by bkosborne** [comment]
So, the reason this is done is to make it easy to setup. The user doesn't need to worry about styling the tracker elements, the carousel will do it. I think most jQuery plugins take this approach - where they only really require that you give it an HTML element and it does all the manipulating itself.

I'm in the middle of a re-write, I'll consider some of this
